export const Spades = [    // 黑桃
    { "id": 1, "pokerNum": "A", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 2, "pokerNum": "2", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 3, "pokerNum": "3", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 4, "pokerNum": "4", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 5, "pokerNum": "5", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 6, "pokerNum": "6", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 7, "pokerNum": "7", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 8, "pokerNum": "8", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 9, "pokerNum": "9", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 10, "pokerNum": "10", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 11, "pokerNum": "J", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 12, "pokerNum": "Q", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 13, "pokerNum": "K", "pokerDecor": "♠", "color": "black", "cardsFace": true },
]
export const RedPeach = [    // 红桃
    { "id": 1, "pokerNum": "A", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 2, "pokerNum": "2", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 3, "pokerNum": "3", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 4, "pokerNum": "4", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 5, "pokerNum": "5", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 6, "pokerNum": "6", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 7, "pokerNum": "7", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 8, "pokerNum": "8", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 9, "pokerNum": "9", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 10, "pokerNum": "10", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 11, "pokerNum": "J", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 12, "pokerNum": "Q", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 13, "pokerNum": "K", "pokerDecor": "♥", "color": "red", "cardsFace": true },
]
export const Block = [    // 方块
    { "id": 1, "pokerNum": "A", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 2, "pokerNum": "2", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 3, "pokerNum": "3", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 4, "pokerNum": "4", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 5, "pokerNum": "5", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 6, "pokerNum": "6", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 7, "pokerNum": "7", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 8, "pokerNum": "8", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 9, "pokerNum": "9", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 10, "pokerNum": "10", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 11, "pokerNum": "J", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 12, "pokerNum": "Q", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 13, "pokerNum": "K", "pokerDecor": "♦", "color": "red", "cardsFace": true },
]
export const PlumBlossom = [    // 梅花
    { "id": 1, "pokerNum": "A", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 2, "pokerNum": "2", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 3, "pokerNum": "3", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 4, "pokerNum": "4", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 5, "pokerNum": "5", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 6, "pokerNum": "6", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 7, "pokerNum": "7", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 8, "pokerNum": "8", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 9, "pokerNum": "9", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 10, "pokerNum": "10", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 11, "pokerNum": "J", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 12, "pokerNum": "Q", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 13, "pokerNum": "K", "pokerDecor": "♣", "color": "black", "cardsFace": true },
]
export const King = [
    { "id": 1, "pokerNum": "JOKER", "pokerDecor": "♕", "color": "red", "cardsFace": true },
    { "id": 2, "pokerNum": "JOKER", "pokerDecor": "♔", "color": "black", "cardsFace": true },
]

// export default { Spades, RedPeach, Block, PlumBlossom, King }