export const Spades = [    // 黑桃
    { "id": 1, "pokerNum": "A", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 2, "pokerNum": "2", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 3, "pokerNum": "3", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 4, "pokerNum": "4", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 5, "pokerNum": "5", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 6, "pokerNum": "6", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 7, "pokerNum": "7", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 8, "pokerNum": "8", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 9, "pokerNum": "9", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 10, "pokerNum": "10", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 11, "pokerNum": "J", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 12, "pokerNum": "Q", "pokerDecor": "♠", "color": "black", "cardsFace": true },
    { "id": 13, "pokerNum": "K", "pokerDecor": "♠", "color": "black", "cardsFace": true },
]
export const RedPeach = [    // 红桃
    { "id": 14, "pokerNum": "A", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 15, "pokerNum": "2", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 16, "pokerNum": "3", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 17, "pokerNum": "4", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 18, "pokerNum": "5", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 19, "pokerNum": "6", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 20, "pokerNum": "7", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 21, "pokerNum": "8", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 22, "pokerNum": "9", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 23, "pokerNum": "10", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 24, "pokerNum": "J", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 25, "pokerNum": "Q", "pokerDecor": "♥", "color": "red", "cardsFace": true },
    { "id": 26, "pokerNum": "K", "pokerDecor": "♥", "color": "red", "cardsFace": true },
]
export const Block = [    // 方块
    { "id": 27, "pokerNum": "A", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 28, "pokerNum": "2", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 29, "pokerNum": "3", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 30, "pokerNum": "4", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 31, "pokerNum": "5", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 32, "pokerNum": "6", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 33, "pokerNum": "7", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 34, "pokerNum": "8", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 45, "pokerNum": "9", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 36, "pokerNum": "10", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 37, "pokerNum": "J", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 38, "pokerNum": "Q", "pokerDecor": "♦", "color": "red", "cardsFace": true },
    { "id": 39, "pokerNum": "K", "pokerDecor": "♦", "color": "red", "cardsFace": true },
]
export const PlumBlossom = [    // 梅花
    { "id": 40, "pokerNum": "A", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 41, "pokerNum": "2", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 42, "pokerNum": "3", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 43, "pokerNum": "4", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 44, "pokerNum": "5", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 45, "pokerNum": "6", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 46, "pokerNum": "7", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 47, "pokerNum": "8", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 48, "pokerNum": "9", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 49, "pokerNum": "10", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 50, "pokerNum": "J", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 51, "pokerNum": "Q", "pokerDecor": "♣", "color": "black", "cardsFace": true },
    { "id": 52, "pokerNum": "K", "pokerDecor": "♣", "color": "black", "cardsFace": true },
]
export const King = [
    { "id": 53, "pokerNum": "JOKER", "pokerDecor": "♕", "color": "red", "cardsFace": true },
    { "id": 54, "pokerNum": "JOKER", "pokerDecor": "♔", "color": "black", "cardsFace": true },
]

// export default { Spades, RedPeach, Block, PlumBlossom, King }